version: 2
project_name: nack
env:
  - VERSION={{ if index .Env "VERSION" }}{{ .Env.VERSION }}{{ else }}{{ .Version }}{{ end }}

release:
  name_template: 'Release {{.Tag}}'
  draft: true
  skip_upload: true
  github:
    owner: nats-io
    name: nack

builds:
  - id: jetstream-controller
    main: ./cmd/jetstream-controller
    binary: jetstream-controller
    ldflags:
      - -s -w -X main.Version={{ .Env.VERSION }} -X main.GitInfo={{.ShortCommit}} -X main.BuildTime={{.Date}}
    tags:
      - timetzdata
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
      - arm64
      - arm
    goarm:
      - 6
      - 7

  - id: nats-boot-config
    main: ./cmd/nats-boot-config
    binary: nats-boot-config
    ldflags:
      - -s -w -X main.Version={{ .Env.VERSION }} -X main.GitInfo={{.ShortCommit}} -X main.BuildTime={{.Date}}
    tags:
      - timetzdata
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
      - arm64
      - arm
    goarm:
      - 6
      - 7

  - id: nats-server-config-reloader
    main: ./cmd/nats-server-config-reloader
    binary: nats-server-config-reloader
    ldflags:
      - -s -w -X main.Version={{ .Env.VERSION }} -X main.GitInfo={{.ShortCommit}} -X main.BuildTime={{.Date}}
    tags:
      - timetzdata
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
      - arm64
      - arm
    goarm:
      - 6
      - 7
