#syntax=docker/dockerfile:1.13
FROM --platform=$BUILDPLATFORM golang:1.24.2-bullseye AS build


RUN <<EOT
    set -e

    echo 'deb [trusted=yes] https://repo.goreleaser.com/apt/ /' > /etc/apt/sources.list.d/goreleaser.list
    apt-get update
    apt-get install -y goreleaser
    rm -rf /var/lib/apt/lists/*
EOT

FROM build

ARG CI
ARG PUSH
ARG GITHUB_TOKEN
ARG TAGS
ARG VERSION

COPY --from=src . /go/src

RUN <<EOT
  set -e
  cd /go/src
  FLAGS="--clean"
  if [ -z ${GITHUB_TOKEN} ]; then
    if [ ${CI} != "true" ]; then FLAGS="${FLAGS} --skip=validate"; fi
    if [ ${PUSH} != "true" ]; then FLAGS="${FLAGS} --single-target"; fi
    goreleaser build ${FLAGS}
  else
    goreleaser release ${FLAGS}
  fi
EOT
