---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: nats-server-tls
spec:
  secretName: nats-server-tls
  duration: 2160h # 90 days
  renewBefore: 240h # 10 days
  issuerRef:
    name: nats-ca
    kind: Issuer
  commonName: nats.default.svc.cluster.local
  dnsNames:
  - nats
  - nats.default
  - nats.default.svc
  - nats.default.svc.cluster.local
  - '*.nats'
  - '*.nats.default'
  - '*.nats.default.svc'
