name: Release
on:
  workflow_dispatch:
  push:
    tags:
      - v[0-9]+.[0-9]+.[0-9]+
jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - name: Checkout Source
      uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      with:
        fetch-depth: 0
        persist-credentials: false

    - name: Setup Go
      uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e # v7.0.0
      with:
        go-version-file: go.mod
        cache: false

    - name: Setup QEMU
      uses: docker/setup-qemu-action@96fe6ef7f33517b61c61be40b68a1882f3264fb8 # v4.2.0

    - name: Setup Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@bb05f3f5519dd87d3ba754cc423b652a5edd6d2c # v4.2.0

    - name: Setup Docker Hub
      uses: docker/login-action@dbcb813823bdd20940b903addbd779551569679f # v4.6.0
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_CLI_TOKEN }}

    - name: Get Image Tags
      id: tags
      run: |
        version=$(sed 's/^v//' <<< ${GITHUB_REF_NAME})
        echo tags="latest,${version}" >> $GITHUB_OUTPUT

    - name: Build and Push
      uses: docker/bake-action@d3418bd7d0e9324001bca92fa8ba175ea7e6dc9b # v7.3.0
      with:
        source: .
        files: docker-bake.hcl
        push: true
        set: goreleaser.args.GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }}
      env:
        TAGS: "${{ steps.tags.outputs.tags }}"
        REGISTRY: "natsio"

    - name: Attach Release Files
      run: gh release upload ${GITHUB_REF_NAME} deploy/crds.yml deploy/rbac.yml
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
